# Generated by Django 4.2.13 on 2024-08-27 12:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('confirm', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='confirm',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='email',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='contents',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='images',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(default='subject', max_length=200, unique=True),
        ),
    ]
