# Generated by Django 3.2.25 on 2024-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieposts',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movieposts',
            name='imdb_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movieposts',
            name='rotten_tomatoes_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movieposts',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
