# Generated by Django 3.2.25 on 2024-07-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frights', '0002_auto_20240723_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieposts',
            name='rotten_tomatoes_rating',
            field=models.SlugField(default=0),
        ),
    ]
