# Generated by Django 3.2.25 on 2024-07-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frights', '0003_alter_movieposts_rotten_tomatoes_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieposts',
            name='our_rating',
            field=models.SlugField(allow_unicode=True, default=0),
        ),
    ]
