# Generated by Django 3.2.25 on 2024-07-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frights', '0003_auto_20240723_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepost',
            name='imdb_rating',
            field=models.TextField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='moviepost',
            name='rotten_tomatoes_rating',
            field=models.TextField(default='0', max_length=3),
        ),
    ]
