# Generated by Django 3.2.25 on 2024-07-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frights', '0004_movieposts_our_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieposts',
            options={'ordering': ['-created_on']},
        ),
    ]
