# Generated by Django 3.2.25 on 2024-07-24 19:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frights', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoviePost',
            new_name='Movie',
        ),
    ]
