# Generated by Django 4.2.13 on 2024-08-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.SlugField(default=0, max_length=4),
        ),
    ]
