# Generated by Django 4.2.13 on 2024-08-19 13:11

from django.db import migrations, models
import emoji_picker.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_our_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='our_rating',
            field=models.CharField(verbose_name=emoji_picker.widgets.EmojiPickerTextareaAdmin),
        ),
    ]
