# Generated by Django 4.2.13 on 2024-08-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_our_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='our_rating',
            field=models.SlugField(allow_unicode=True, default=0),
        ),
    ]
