# Generated by Django 4.2.13 on 2024-08-21 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0007_rename_post_comment_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
