# Generated by Django 4.2.13 on 2024-08-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_rename_movie_comment_post_alter_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='our_rating',
            field=models.TextField(default='0', max_length=5),
        ),
    ]
