# Generated by Django 4.2.13 on 2024-08-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_our_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='our_rating',
            field=models.TextField(default='0', max_length=26),
        ),
    ]
