# Generated by Django 4.2.13 on 2024-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_rename_post_comment_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('movie_title', models.TextField()),
                ('additional_comments', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
