# Generated by Django 4.2.13 on 2024-08-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_recommendmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendmovie',
            name='additional_comments',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recommendmovie',
            name='movie_title',
            field=models.TextField(max_length=200),
        ),
    ]
