# Generated by Django 4.2.13 on 2024-08-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_recommendmovie_additional_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_rating',
        ),
    ]
